// <autogenerated />
namespace Felt_32_European_32_Traditional
{
    partial class MainForm
    {
        /// <summary>
        /// Designer variable used to keep track of non-visual components.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Disposes resources used by the form.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This method is required for Windows Forms designer support.
        /// Do not change the method contents inside the source code editor. The Forms designer might
        /// not be able to load this method if it was changed manually.
        /// </summary>
        private void InitializeComponent()
        {
        	this.mainTableLayoutPanel = new System.Windows.Forms.TableLayoutPanel();
        	this.undoButton = new System.Windows.Forms.Button();
        	this.button0 = new System.Windows.Forms.Button();
        	this.button1 = new System.Windows.Forms.Button();
        	this.button2 = new System.Windows.Forms.Button();
        	this.button3 = new System.Windows.Forms.Button();
        	this.button4 = new System.Windows.Forms.Button();
        	this.button5 = new System.Windows.Forms.Button();
        	this.button6 = new System.Windows.Forms.Button();
        	this.button7 = new System.Windows.Forms.Button();
        	this.button8 = new System.Windows.Forms.Button();
        	this.button9 = new System.Windows.Forms.Button();
        	this.button10 = new System.Windows.Forms.Button();
        	this.button11 = new System.Windows.Forms.Button();
        	this.button12 = new System.Windows.Forms.Button();
        	this.button13 = new System.Windows.Forms.Button();
        	this.button14 = new System.Windows.Forms.Button();
        	this.button15 = new System.Windows.Forms.Button();
        	this.button16 = new System.Windows.Forms.Button();
        	this.button17 = new System.Windows.Forms.Button();
        	this.button18 = new System.Windows.Forms.Button();
        	this.button19 = new System.Windows.Forms.Button();
        	this.button20 = new System.Windows.Forms.Button();
        	this.button21 = new System.Windows.Forms.Button();
        	this.button22 = new System.Windows.Forms.Button();
        	this.button23 = new System.Windows.Forms.Button();
        	this.button24 = new System.Windows.Forms.Button();
        	this.button25 = new System.Windows.Forms.Button();
        	this.button26 = new System.Windows.Forms.Button();
        	this.button27 = new System.Windows.Forms.Button();
        	this.button28 = new System.Windows.Forms.Button();
        	this.button29 = new System.Windows.Forms.Button();
        	this.button30 = new System.Windows.Forms.Button();
        	this.button31 = new System.Windows.Forms.Button();
        	this.button32 = new System.Windows.Forms.Button();
        	this.button33 = new System.Windows.Forms.Button();
        	this.button34 = new System.Windows.Forms.Button();
        	this.button35 = new System.Windows.Forms.Button();
        	this.button36 = new System.Windows.Forms.Button();
        	this.mainMenuStrip = new System.Windows.Forms.MenuStrip();
        	this.editToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.undoToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
        	this.aboutToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
        	this.mainTableLayoutPanel.SuspendLayout();
        	this.mainMenuStrip.SuspendLayout();
        	this.SuspendLayout();
        	// 
        	// mainTableLayoutPanel
        	// 
        	this.mainTableLayoutPanel.ColumnCount = 3;
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33332F));
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 33.33334F));
        	this.mainTableLayoutPanel.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Absolute, 1F));
        	this.mainTableLayoutPanel.Controls.Add(this.undoButton, 0, 13);
        	this.mainTableLayoutPanel.Controls.Add(this.button0, 0, 0);
        	this.mainTableLayoutPanel.Controls.Add(this.button1, 0, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.button2, 1, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.button3, 2, 1);
        	this.mainTableLayoutPanel.Controls.Add(this.button4, 0, 2);
        	this.mainTableLayoutPanel.Controls.Add(this.button5, 1, 2);
        	this.mainTableLayoutPanel.Controls.Add(this.button6, 2, 2);
        	this.mainTableLayoutPanel.Controls.Add(this.button7, 0, 3);
        	this.mainTableLayoutPanel.Controls.Add(this.button8, 1, 3);
        	this.mainTableLayoutPanel.Controls.Add(this.button9, 2, 3);
        	this.mainTableLayoutPanel.Controls.Add(this.button10, 0, 4);
        	this.mainTableLayoutPanel.Controls.Add(this.button11, 1, 4);
        	this.mainTableLayoutPanel.Controls.Add(this.button12, 2, 4);
        	this.mainTableLayoutPanel.Controls.Add(this.button13, 0, 5);
        	this.mainTableLayoutPanel.Controls.Add(this.button14, 1, 5);
        	this.mainTableLayoutPanel.Controls.Add(this.button15, 2, 5);
        	this.mainTableLayoutPanel.Controls.Add(this.button16, 0, 6);
        	this.mainTableLayoutPanel.Controls.Add(this.button17, 1, 6);
        	this.mainTableLayoutPanel.Controls.Add(this.button18, 2, 6);
        	this.mainTableLayoutPanel.Controls.Add(this.button19, 0, 7);
        	this.mainTableLayoutPanel.Controls.Add(this.button20, 1, 7);
        	this.mainTableLayoutPanel.Controls.Add(this.button21, 2, 7);
        	this.mainTableLayoutPanel.Controls.Add(this.button22, 0, 8);
        	this.mainTableLayoutPanel.Controls.Add(this.button23, 1, 8);
        	this.mainTableLayoutPanel.Controls.Add(this.button24, 2, 8);
        	this.mainTableLayoutPanel.Controls.Add(this.button25, 0, 9);
        	this.mainTableLayoutPanel.Controls.Add(this.button26, 1, 9);
        	this.mainTableLayoutPanel.Controls.Add(this.button27, 2, 9);
        	this.mainTableLayoutPanel.Controls.Add(this.button28, 0, 10);
        	this.mainTableLayoutPanel.Controls.Add(this.button29, 1, 10);
        	this.mainTableLayoutPanel.Controls.Add(this.button30, 2, 10);
        	this.mainTableLayoutPanel.Controls.Add(this.button31, 0, 11);
        	this.mainTableLayoutPanel.Controls.Add(this.button32, 1, 11);
        	this.mainTableLayoutPanel.Controls.Add(this.button33, 2, 11);
        	this.mainTableLayoutPanel.Controls.Add(this.button34, 0, 12);
        	this.mainTableLayoutPanel.Controls.Add(this.button35, 1, 12);
        	this.mainTableLayoutPanel.Controls.Add(this.button36, 2, 12);
        	this.mainTableLayoutPanel.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.mainTableLayoutPanel.Location = new System.Drawing.Point(0, 24);
        	this.mainTableLayoutPanel.Margin = new System.Windows.Forms.Padding(1);
        	this.mainTableLayoutPanel.Name = "mainTableLayoutPanel";
        	this.mainTableLayoutPanel.Padding = new System.Windows.Forms.Padding(0, 1, 0, 1);
        	this.mainTableLayoutPanel.RowCount = 14;
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.142714F));
        	this.mainTableLayoutPanel.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.144711F));
        	this.mainTableLayoutPanel.Size = new System.Drawing.Size(244, 536);
        	this.mainTableLayoutPanel.TabIndex = 3;
        	// 
        	// undoButton
        	// 
        	this.undoButton.BackColor = System.Drawing.Color.Navy;
        	this.mainTableLayoutPanel.SetColumnSpan(this.undoButton, 3);
        	this.undoButton.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.undoButton.ForeColor = System.Drawing.Color.White;
        	this.undoButton.Location = new System.Drawing.Point(1, 496);
        	this.undoButton.Margin = new System.Windows.Forms.Padding(1);
        	this.undoButton.Name = "undoButton";
        	this.undoButton.Size = new System.Drawing.Size(242, 38);
        	this.undoButton.TabIndex = 37;
        	this.undoButton.Text = "&Undo";
        	this.undoButton.UseVisualStyleBackColor = false;
        	this.undoButton.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.undoButton.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button0
        	// 
        	this.button0.BackColor = System.Drawing.Color.Green;
        	this.mainTableLayoutPanel.SetColumnSpan(this.button0, 3);
        	this.button0.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button0.Location = new System.Drawing.Point(1, 2);
        	this.button0.Margin = new System.Windows.Forms.Padding(1);
        	this.button0.Name = "button0";
        	this.button0.Size = new System.Drawing.Size(242, 36);
        	this.button0.TabIndex = 38;
        	this.button0.Text = "0";
        	this.button0.UseVisualStyleBackColor = false;
        	this.button0.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button0.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button0.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button1
        	// 
        	this.button1.BackColor = System.Drawing.Color.Red;
        	this.button1.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button1.Location = new System.Drawing.Point(1, 40);
        	this.button1.Margin = new System.Windows.Forms.Padding(1);
        	this.button1.Name = "button1";
        	this.button1.Size = new System.Drawing.Size(79, 36);
        	this.button1.TabIndex = 39;
        	this.button1.Text = "1";
        	this.button1.UseVisualStyleBackColor = false;
        	this.button1.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button1.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button1.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button2
        	// 
        	this.button2.BackColor = System.Drawing.Color.Black;
        	this.button2.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button2.Location = new System.Drawing.Point(82, 40);
        	this.button2.Margin = new System.Windows.Forms.Padding(1);
        	this.button2.Name = "button2";
        	this.button2.Size = new System.Drawing.Size(79, 36);
        	this.button2.TabIndex = 40;
        	this.button2.Text = "2";
        	this.button2.UseVisualStyleBackColor = false;
        	this.button2.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button2.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button2.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button3
        	// 
        	this.button3.BackColor = System.Drawing.Color.Red;
        	this.button3.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button3.Location = new System.Drawing.Point(163, 40);
        	this.button3.Margin = new System.Windows.Forms.Padding(1);
        	this.button3.Name = "button3";
        	this.button3.Size = new System.Drawing.Size(80, 36);
        	this.button3.TabIndex = 41;
        	this.button3.Text = "3";
        	this.button3.UseVisualStyleBackColor = false;
        	this.button3.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button3.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button3.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button4
        	// 
        	this.button4.BackColor = System.Drawing.Color.Black;
        	this.button4.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button4.Location = new System.Drawing.Point(1, 78);
        	this.button4.Margin = new System.Windows.Forms.Padding(1);
        	this.button4.Name = "button4";
        	this.button4.Size = new System.Drawing.Size(79, 36);
        	this.button4.TabIndex = 42;
        	this.button4.Text = "4";
        	this.button4.UseVisualStyleBackColor = false;
        	this.button4.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button4.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button4.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button5
        	// 
        	this.button5.BackColor = System.Drawing.Color.Red;
        	this.button5.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button5.Location = new System.Drawing.Point(82, 78);
        	this.button5.Margin = new System.Windows.Forms.Padding(1);
        	this.button5.Name = "button5";
        	this.button5.Size = new System.Drawing.Size(79, 36);
        	this.button5.TabIndex = 43;
        	this.button5.Text = "5";
        	this.button5.UseVisualStyleBackColor = false;
        	this.button5.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button5.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button5.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button6
        	// 
        	this.button6.BackColor = System.Drawing.Color.Black;
        	this.button6.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button6.Location = new System.Drawing.Point(163, 78);
        	this.button6.Margin = new System.Windows.Forms.Padding(1);
        	this.button6.Name = "button6";
        	this.button6.Size = new System.Drawing.Size(80, 36);
        	this.button6.TabIndex = 44;
        	this.button6.Text = "6";
        	this.button6.UseVisualStyleBackColor = false;
        	this.button6.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button6.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button6.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button7
        	// 
        	this.button7.BackColor = System.Drawing.Color.Red;
        	this.button7.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button7.Location = new System.Drawing.Point(1, 116);
        	this.button7.Margin = new System.Windows.Forms.Padding(1);
        	this.button7.Name = "button7";
        	this.button7.Size = new System.Drawing.Size(79, 36);
        	this.button7.TabIndex = 45;
        	this.button7.Text = "7";
        	this.button7.UseVisualStyleBackColor = false;
        	this.button7.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button7.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button7.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button8
        	// 
        	this.button8.BackColor = System.Drawing.Color.Black;
        	this.button8.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button8.Location = new System.Drawing.Point(82, 116);
        	this.button8.Margin = new System.Windows.Forms.Padding(1);
        	this.button8.Name = "button8";
        	this.button8.Size = new System.Drawing.Size(79, 36);
        	this.button8.TabIndex = 46;
        	this.button8.Text = "8";
        	this.button8.UseVisualStyleBackColor = false;
        	this.button8.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button8.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button8.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button9
        	// 
        	this.button9.BackColor = System.Drawing.Color.Red;
        	this.button9.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button9.Location = new System.Drawing.Point(163, 116);
        	this.button9.Margin = new System.Windows.Forms.Padding(1);
        	this.button9.Name = "button9";
        	this.button9.Size = new System.Drawing.Size(80, 36);
        	this.button9.TabIndex = 47;
        	this.button9.Text = "9";
        	this.button9.UseVisualStyleBackColor = false;
        	this.button9.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button9.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button9.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button10
        	// 
        	this.button10.BackColor = System.Drawing.Color.Black;
        	this.button10.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button10.Location = new System.Drawing.Point(1, 154);
        	this.button10.Margin = new System.Windows.Forms.Padding(1);
        	this.button10.Name = "button10";
        	this.button10.Size = new System.Drawing.Size(79, 36);
        	this.button10.TabIndex = 48;
        	this.button10.Text = "10";
        	this.button10.UseVisualStyleBackColor = false;
        	this.button10.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button10.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button10.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button11
        	// 
        	this.button11.BackColor = System.Drawing.Color.Black;
        	this.button11.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button11.Location = new System.Drawing.Point(82, 154);
        	this.button11.Margin = new System.Windows.Forms.Padding(1);
        	this.button11.Name = "button11";
        	this.button11.Size = new System.Drawing.Size(79, 36);
        	this.button11.TabIndex = 49;
        	this.button11.Text = "11";
        	this.button11.UseVisualStyleBackColor = false;
        	this.button11.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button11.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button11.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button12
        	// 
        	this.button12.BackColor = System.Drawing.Color.Red;
        	this.button12.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button12.Location = new System.Drawing.Point(163, 154);
        	this.button12.Margin = new System.Windows.Forms.Padding(1);
        	this.button12.Name = "button12";
        	this.button12.Size = new System.Drawing.Size(80, 36);
        	this.button12.TabIndex = 50;
        	this.button12.Text = "12";
        	this.button12.UseVisualStyleBackColor = false;
        	this.button12.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button12.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button12.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button13
        	// 
        	this.button13.BackColor = System.Drawing.Color.Black;
        	this.button13.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button13.Location = new System.Drawing.Point(1, 192);
        	this.button13.Margin = new System.Windows.Forms.Padding(1);
        	this.button13.Name = "button13";
        	this.button13.Size = new System.Drawing.Size(79, 36);
        	this.button13.TabIndex = 51;
        	this.button13.Text = "13";
        	this.button13.UseVisualStyleBackColor = false;
        	this.button13.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button13.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button13.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button14
        	// 
        	this.button14.BackColor = System.Drawing.Color.Red;
        	this.button14.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button14.Location = new System.Drawing.Point(82, 192);
        	this.button14.Margin = new System.Windows.Forms.Padding(1);
        	this.button14.Name = "button14";
        	this.button14.Size = new System.Drawing.Size(79, 36);
        	this.button14.TabIndex = 52;
        	this.button14.Text = "14";
        	this.button14.UseVisualStyleBackColor = false;
        	this.button14.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button14.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button14.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button15
        	// 
        	this.button15.BackColor = System.Drawing.Color.Black;
        	this.button15.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button15.Location = new System.Drawing.Point(163, 192);
        	this.button15.Margin = new System.Windows.Forms.Padding(1);
        	this.button15.Name = "button15";
        	this.button15.Size = new System.Drawing.Size(80, 36);
        	this.button15.TabIndex = 53;
        	this.button15.Text = "15";
        	this.button15.UseVisualStyleBackColor = false;
        	this.button15.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button15.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button15.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button16
        	// 
        	this.button16.BackColor = System.Drawing.Color.Red;
        	this.button16.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button16.Location = new System.Drawing.Point(1, 230);
        	this.button16.Margin = new System.Windows.Forms.Padding(1);
        	this.button16.Name = "button16";
        	this.button16.Size = new System.Drawing.Size(79, 36);
        	this.button16.TabIndex = 54;
        	this.button16.Text = "16";
        	this.button16.UseVisualStyleBackColor = false;
        	this.button16.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button16.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button16.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button17
        	// 
        	this.button17.BackColor = System.Drawing.Color.Black;
        	this.button17.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button17.Location = new System.Drawing.Point(82, 230);
        	this.button17.Margin = new System.Windows.Forms.Padding(1);
        	this.button17.Name = "button17";
        	this.button17.Size = new System.Drawing.Size(79, 36);
        	this.button17.TabIndex = 55;
        	this.button17.Text = "17";
        	this.button17.UseVisualStyleBackColor = false;
        	this.button17.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button17.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button17.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button18
        	// 
        	this.button18.BackColor = System.Drawing.Color.Red;
        	this.button18.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button18.Location = new System.Drawing.Point(163, 230);
        	this.button18.Margin = new System.Windows.Forms.Padding(1);
        	this.button18.Name = "button18";
        	this.button18.Size = new System.Drawing.Size(80, 36);
        	this.button18.TabIndex = 56;
        	this.button18.Text = "18";
        	this.button18.UseVisualStyleBackColor = false;
        	this.button18.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button18.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button18.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button19
        	// 
        	this.button19.BackColor = System.Drawing.Color.Red;
        	this.button19.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button19.Location = new System.Drawing.Point(1, 268);
        	this.button19.Margin = new System.Windows.Forms.Padding(1);
        	this.button19.Name = "button19";
        	this.button19.Size = new System.Drawing.Size(79, 36);
        	this.button19.TabIndex = 57;
        	this.button19.Text = "19";
        	this.button19.UseVisualStyleBackColor = false;
        	this.button19.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button19.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button19.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button20
        	// 
        	this.button20.BackColor = System.Drawing.Color.Black;
        	this.button20.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button20.Location = new System.Drawing.Point(82, 268);
        	this.button20.Margin = new System.Windows.Forms.Padding(1);
        	this.button20.Name = "button20";
        	this.button20.Size = new System.Drawing.Size(79, 36);
        	this.button20.TabIndex = 58;
        	this.button20.Text = "20";
        	this.button20.UseVisualStyleBackColor = false;
        	this.button20.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button20.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button20.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button21
        	// 
        	this.button21.BackColor = System.Drawing.Color.Red;
        	this.button21.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button21.Location = new System.Drawing.Point(163, 268);
        	this.button21.Margin = new System.Windows.Forms.Padding(1);
        	this.button21.Name = "button21";
        	this.button21.Size = new System.Drawing.Size(80, 36);
        	this.button21.TabIndex = 59;
        	this.button21.Text = "21";
        	this.button21.UseVisualStyleBackColor = false;
        	this.button21.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button21.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button21.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button22
        	// 
        	this.button22.BackColor = System.Drawing.Color.Black;
        	this.button22.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button22.Location = new System.Drawing.Point(1, 306);
        	this.button22.Margin = new System.Windows.Forms.Padding(1);
        	this.button22.Name = "button22";
        	this.button22.Size = new System.Drawing.Size(79, 36);
        	this.button22.TabIndex = 60;
        	this.button22.Text = "22";
        	this.button22.UseVisualStyleBackColor = false;
        	this.button22.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button22.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button22.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button23
        	// 
        	this.button23.BackColor = System.Drawing.Color.Red;
        	this.button23.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button23.Location = new System.Drawing.Point(82, 306);
        	this.button23.Margin = new System.Windows.Forms.Padding(1);
        	this.button23.Name = "button23";
        	this.button23.Size = new System.Drawing.Size(79, 36);
        	this.button23.TabIndex = 61;
        	this.button23.Text = "23";
        	this.button23.UseVisualStyleBackColor = false;
        	this.button23.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button23.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button23.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button24
        	// 
        	this.button24.BackColor = System.Drawing.Color.Black;
        	this.button24.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button24.Location = new System.Drawing.Point(163, 306);
        	this.button24.Margin = new System.Windows.Forms.Padding(1);
        	this.button24.Name = "button24";
        	this.button24.Size = new System.Drawing.Size(80, 36);
        	this.button24.TabIndex = 62;
        	this.button24.Text = "24";
        	this.button24.UseVisualStyleBackColor = false;
        	this.button24.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button24.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button24.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button25
        	// 
        	this.button25.BackColor = System.Drawing.Color.Red;
        	this.button25.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button25.Location = new System.Drawing.Point(1, 344);
        	this.button25.Margin = new System.Windows.Forms.Padding(1);
        	this.button25.Name = "button25";
        	this.button25.Size = new System.Drawing.Size(79, 36);
        	this.button25.TabIndex = 63;
        	this.button25.Text = "25";
        	this.button25.UseVisualStyleBackColor = false;
        	this.button25.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button25.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button25.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button26
        	// 
        	this.button26.BackColor = System.Drawing.Color.Black;
        	this.button26.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button26.Location = new System.Drawing.Point(82, 344);
        	this.button26.Margin = new System.Windows.Forms.Padding(1);
        	this.button26.Name = "button26";
        	this.button26.Size = new System.Drawing.Size(79, 36);
        	this.button26.TabIndex = 64;
        	this.button26.Text = "26";
        	this.button26.UseVisualStyleBackColor = false;
        	this.button26.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button26.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button26.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button27
        	// 
        	this.button27.BackColor = System.Drawing.Color.Red;
        	this.button27.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button27.Location = new System.Drawing.Point(163, 344);
        	this.button27.Margin = new System.Windows.Forms.Padding(1);
        	this.button27.Name = "button27";
        	this.button27.Size = new System.Drawing.Size(80, 36);
        	this.button27.TabIndex = 65;
        	this.button27.Text = "27";
        	this.button27.UseVisualStyleBackColor = false;
        	this.button27.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button27.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button27.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button28
        	// 
        	this.button28.BackColor = System.Drawing.Color.Black;
        	this.button28.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button28.Location = new System.Drawing.Point(1, 382);
        	this.button28.Margin = new System.Windows.Forms.Padding(1);
        	this.button28.Name = "button28";
        	this.button28.Size = new System.Drawing.Size(79, 36);
        	this.button28.TabIndex = 66;
        	this.button28.Text = "28";
        	this.button28.UseVisualStyleBackColor = false;
        	this.button28.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button28.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button28.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button29
        	// 
        	this.button29.BackColor = System.Drawing.Color.Black;
        	this.button29.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button29.Location = new System.Drawing.Point(82, 382);
        	this.button29.Margin = new System.Windows.Forms.Padding(1);
        	this.button29.Name = "button29";
        	this.button29.Size = new System.Drawing.Size(79, 36);
        	this.button29.TabIndex = 67;
        	this.button29.Text = "29";
        	this.button29.UseVisualStyleBackColor = false;
        	this.button29.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button29.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button29.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button30
        	// 
        	this.button30.BackColor = System.Drawing.Color.Red;
        	this.button30.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button30.Location = new System.Drawing.Point(163, 382);
        	this.button30.Margin = new System.Windows.Forms.Padding(1);
        	this.button30.Name = "button30";
        	this.button30.Size = new System.Drawing.Size(80, 36);
        	this.button30.TabIndex = 68;
        	this.button30.Text = "30";
        	this.button30.UseVisualStyleBackColor = false;
        	this.button30.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button30.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button30.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button31
        	// 
        	this.button31.BackColor = System.Drawing.Color.Black;
        	this.button31.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button31.Location = new System.Drawing.Point(1, 420);
        	this.button31.Margin = new System.Windows.Forms.Padding(1);
        	this.button31.Name = "button31";
        	this.button31.Size = new System.Drawing.Size(79, 36);
        	this.button31.TabIndex = 69;
        	this.button31.Text = "31";
        	this.button31.UseVisualStyleBackColor = false;
        	this.button31.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button31.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button31.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button32
        	// 
        	this.button32.BackColor = System.Drawing.Color.Red;
        	this.button32.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button32.Location = new System.Drawing.Point(82, 420);
        	this.button32.Margin = new System.Windows.Forms.Padding(1);
        	this.button32.Name = "button32";
        	this.button32.Size = new System.Drawing.Size(79, 36);
        	this.button32.TabIndex = 70;
        	this.button32.Text = "32";
        	this.button32.UseVisualStyleBackColor = false;
        	this.button32.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button32.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button32.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button33
        	// 
        	this.button33.BackColor = System.Drawing.Color.Black;
        	this.button33.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button33.Location = new System.Drawing.Point(163, 420);
        	this.button33.Margin = new System.Windows.Forms.Padding(1);
        	this.button33.Name = "button33";
        	this.button33.Size = new System.Drawing.Size(80, 36);
        	this.button33.TabIndex = 71;
        	this.button33.Text = "33";
        	this.button33.UseVisualStyleBackColor = false;
        	this.button33.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button33.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button33.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button34
        	// 
        	this.button34.BackColor = System.Drawing.Color.Red;
        	this.button34.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button34.Location = new System.Drawing.Point(1, 458);
        	this.button34.Margin = new System.Windows.Forms.Padding(1);
        	this.button34.Name = "button34";
        	this.button34.Size = new System.Drawing.Size(79, 36);
        	this.button34.TabIndex = 72;
        	this.button34.Text = "34";
        	this.button34.UseVisualStyleBackColor = false;
        	this.button34.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button34.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button34.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button35
        	// 
        	this.button35.BackColor = System.Drawing.Color.Black;
        	this.button35.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button35.Location = new System.Drawing.Point(82, 458);
        	this.button35.Margin = new System.Windows.Forms.Padding(1);
        	this.button35.Name = "button35";
        	this.button35.Size = new System.Drawing.Size(79, 36);
        	this.button35.TabIndex = 73;
        	this.button35.Text = "35";
        	this.button35.UseVisualStyleBackColor = false;
        	this.button35.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button35.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button35.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// button36
        	// 
        	this.button36.BackColor = System.Drawing.Color.Red;
        	this.button36.Dock = System.Windows.Forms.DockStyle.Fill;
        	this.button36.Location = new System.Drawing.Point(163, 458);
        	this.button36.Margin = new System.Windows.Forms.Padding(1);
        	this.button36.Name = "button36";
        	this.button36.Size = new System.Drawing.Size(80, 36);
        	this.button36.TabIndex = 74;
        	this.button36.Text = "36";
        	this.button36.UseVisualStyleBackColor = false;
        	this.button36.Click += new System.EventHandler(this.OnNumberButtonClick);
        	this.button36.MouseEnter += new System.EventHandler(this.OnButtonMouseEnter);
        	this.button36.MouseLeave += new System.EventHandler(this.OnButtonMouseLeave);
        	// 
        	// mainMenuStrip
        	// 
        	this.mainMenuStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.editToolStripMenuItem,
        	        	        	this.helpToolStripMenuItem});
        	this.mainMenuStrip.Location = new System.Drawing.Point(0, 0);
        	this.mainMenuStrip.Name = "mainMenuStrip";
        	this.mainMenuStrip.Padding = new System.Windows.Forms.Padding(1, 1, 0, 1);
        	this.mainMenuStrip.Size = new System.Drawing.Size(244, 24);
        	this.mainMenuStrip.TabIndex = 4;
        	this.mainMenuStrip.Text = "menuStrip1";
        	// 
        	// editToolStripMenuItem
        	// 
        	this.editToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.undoToolStripMenuItem});
        	this.editToolStripMenuItem.Name = "editToolStripMenuItem";
        	this.editToolStripMenuItem.Size = new System.Drawing.Size(37, 22);
        	this.editToolStripMenuItem.Text = "&Edit";
        	// 
        	// undoToolStripMenuItem
        	// 
        	this.undoToolStripMenuItem.Name = "undoToolStripMenuItem";
        	this.undoToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.Z)));
        	this.undoToolStripMenuItem.Size = new System.Drawing.Size(137, 22);
        	this.undoToolStripMenuItem.Text = "&Undo";
        	this.undoToolStripMenuItem.Click += new System.EventHandler(this.OnUndoToolStripMenuItemClick);
        	// 
        	// helpToolStripMenuItem
        	// 
        	this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
        	        	        	this.toolStripSeparator1,
        	        	        	this.aboutToolStripMenuItem});
        	this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
        	this.helpToolStripMenuItem.Size = new System.Drawing.Size(40, 22);
        	this.helpToolStripMenuItem.Text = "&Help";
        	// 
        	// toolStripSeparator1
        	// 
        	this.toolStripSeparator1.Name = "toolStripSeparator1";
        	this.toolStripSeparator1.Size = new System.Drawing.Size(151, 6);
        	// 
        	// aboutToolStripMenuItem
        	// 
        	this.aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
        	this.aboutToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.A)));
        	this.aboutToolStripMenuItem.Size = new System.Drawing.Size(154, 22);
        	this.aboutToolStripMenuItem.Text = "&About...";
        	this.aboutToolStripMenuItem.Click += new System.EventHandler(this.OnAboutToolStripMenuItemClick);
        	// 
        	// MainForm
        	// 
        	this.AutoScaleDimensions = new System.Drawing.SizeF(10F, 20F);
        	this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        	this.BackColor = System.Drawing.Color.DarkGreen;
        	this.ClientSize = new System.Drawing.Size(244, 560);
        	this.Controls.Add(this.mainTableLayoutPanel);
        	this.Controls.Add(this.mainMenuStrip);
        	this.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
        	this.ForeColor = System.Drawing.Color.White;
        	this.MainMenuStrip = this.mainMenuStrip;
        	this.Name = "MainForm";
        	this.Text = "Felt European Traditional";
        	this.mainTableLayoutPanel.ResumeLayout(false);
        	this.mainMenuStrip.ResumeLayout(false);
        	this.mainMenuStrip.PerformLayout();
        	this.ResumeLayout(false);
        	this.PerformLayout();
        }
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem undoToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem editToolStripMenuItem;
        private System.Windows.Forms.MenuStrip mainMenuStrip;

        private System.Windows.Forms.Button button36;
        private System.Windows.Forms.Button button35;
        private System.Windows.Forms.Button button34;
        private System.Windows.Forms.Button button33;
        private System.Windows.Forms.Button button32;
        private System.Windows.Forms.Button button31;
        private System.Windows.Forms.Button button30;
        private System.Windows.Forms.Button button29;
        private System.Windows.Forms.Button button28;
        private System.Windows.Forms.Button button27;
        private System.Windows.Forms.Button button26;
        private System.Windows.Forms.Button button25;
        private System.Windows.Forms.Button button24;
        private System.Windows.Forms.Button button23;
        private System.Windows.Forms.Button button22;
        private System.Windows.Forms.Button button21;
        private System.Windows.Forms.Button button20;
        private System.Windows.Forms.Button button19;
        private System.Windows.Forms.Button button18;
        private System.Windows.Forms.Button button17;
        private System.Windows.Forms.Button button16;
        private System.Windows.Forms.Button button15;
        private System.Windows.Forms.Button button14;
        private System.Windows.Forms.Button button13;
        private System.Windows.Forms.Button button12;
        private System.Windows.Forms.Button button11;
        private System.Windows.Forms.Button button10;
        private System.Windows.Forms.Button button9;
        private System.Windows.Forms.Button button8;
        private System.Windows.Forms.Button button7;
        private System.Windows.Forms.Button button6;
        private System.Windows.Forms.Button button5;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Button button0;
        private System.Windows.Forms.Button undoButton;
        private System.Windows.Forms.TableLayoutPanel mainTableLayoutPanel;
    }
}
